name: My CI Pipeline

on:
  workflow_dispatch:   

jobs:
  build:
    runs-on: self-hosted

    steps:             # ⚡ yeh line missing thi
      - name: Run a script
        run: echo "oye seekh gaya main t ye github action runner bhi "
